export { BrowserIcon } from './BrowserIcon'
export { ChromeIcon } from './ChromeIcon'
export { DesctopIcon } from './DesctopIcon'
export { FireFoxIcon } from './FireFoxIcon'
export { MobileIcon } from './MobileIcon'
export { OperaIcon } from './OperaIcon'
