export const ROUTES_URL = {
  ACCOUNT_MANAGEMENT: '/profile/settings/management',
  CREATE: '/create',
  DEVICES: '/profile/settings/devices',
  FAVORITES: '/favorites',
  FORGOT_PASSWORD: '/forgot-password',
  GENERAL_INFO: '/profile/settings/general',
  HOME: '/',
  MESSENGER: '/messenger',
  MY_PAYMENTS: '/profile/settings/payments',
  PRIVACY_POLICY: '/privacy-policy',
  PROFILE: '/profile',
  SEARCH: '/search',
  SIGN_IN: '/sign-in',
  SIGN_UP: '/sign-up',
  STATISTICS: '/statistics',
  TERMS_OF_SERVICE: '/terms-of-service',
}
